# DO NOT PUT REAL API KEYS IN THE FILE!!
# ONLY EDIT THIS FILE TO ADD NEW DEFAULT API KEYS
#
# USE THE apikeys.sh FILE FOR REAL API KEYS AS IT IS EXCLUDED FROM GIT

export ETHPLORER_API_KEY="freekey"
export INTERCOM_APP_ID=""
export INTERCOM_API_KEY=""
